BOOT_EVENT = 6005
BOOT_EVENT2 = 12
SHUTDOWN_EVENT = 6006
SHUTDOWN_EVENT2 = 13
POWER_LESS = 41
CRASH_EVENT = 6008
RESTART_EVENT = 1074
CRASH_REASON = 1076

EVENT_NAMES = {
    BOOT_EVENT: "BOOT",
    BOOT_EVENT2: "BOOT2",
    SHUTDOWN_EVENT: "SHUTDOWN",
    SHUTDOWN_EVENT2: "SHUTDOWN2",
    POWER_LESS: "POWER_LESS",
    CRASH_EVENT: "CRASH",
    RESTART_EVENT: "RESTART",
    CRASH_REASON: "CRASH_REASON"
}